name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:

jobs:
  build:
    uses: Gravitate-Health/reusable-workflows/.github/workflows/main.yml@main
    secrets: inherit  # Pass secrets from calling workflow
    permissions:
      contents: read
      packages: write
