name: Test and Upload Lenses

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'

jobs:
  # This workflow will:
  # 1. Test lenses with batch-test
  # 2. Upload to dev server on push to any branch
  # 3. Upload to prod server only when a tag is pushed
  upload-lenses:
    uses: Gravitate-Health/reusable-workflows/.github/workflows/lenses-upload.yaml@main
    with:
      # Only pass tag when the trigger is actually a tag push
      tag: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '' }}
